DROP TABLE IF EXISTS public.projects CASCADE;
DROP TYPE IF EXISTS public."current_status" CASCADE;

CREATE TYPE public."current_status" AS ENUM (
	'in-progess',
	'completed');

CREATE TABLE public.projects (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	name text NOT NULL,
	slug text NOT NULL,
	status text DEFAULT 'in-progress'::text NOT NULL,
	collaborators text array DEFAULT array[]::varchar[] NOT NULL,
	CONSTRAINT projects_pkey PRIMARY KEY (id),
	CONSTRAINT projects_slug_key UNIQUE (slug)
);